# Generated by Django 2.1.4 on 2019-03-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Img',
            new_name='Image',
        ),
    ]
