# Generated by Django 2.1.4 on 2019-03-16 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0002_auto_20190305_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='cvt_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='編集タイプ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='edittedImg',
            field=models.FileField(default=django.utils.timezone.now, upload_to='edittedImg/', verbose_name='加工した画像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, primary_key=True, serialize=False, verbose_name='画像名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to='img/', verbose_name='加工したい画像'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
