# Generated by Django 2.2.2 on 2019-06-03 21:43

from django.db import migrations, models
import imgapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0003_auto_20190316_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to=imgapp.models.get_image_path, verbose_name='加工したい画像'),
        ),
    ]
